"$schema" = 'https://starship.rs/config-schema.json'
format = """\
${status}\
${directory}\
${git_branch}\
${git_status}\
${python}\
${character}\
"""

add_newline = false
[character]
format = "[](bg:black)[$symbol](bold) "
success_symbol = "[](fg:black black)"
error_symbol = "[](fg:black black)"
disabled = false

[username]
style_root = 'bg:black bold red'
style_user = 'bg:black yellow'
format = '[$user]($style)'

[status]
disabled = false
style = "bg:black red"
symbol = "✗"
format = "[$symbol]($style)"

[hostname]
ssh_only = true
style = 'bg:black bold dimmed green'
format = "[ $hostname ]($style)"

[directory]
style = "bg:black white"
format = '[$path]($style)[$read_only]($read_only_style)'
repo_root_format = '[$before_root_path]($before_repo_root_style)[$repo_root]($repo_root_style)[$path]($style )[$read_only ]($read_only_style)'
repo_root_style = "bg:black bold white"
before_repo_root_style = "bg:black blue"
read_only = "[\uf023]"
read_only_style = "bg:black red"
truncate_to_repo = true
truncation_length = 5

[time]
disabled = true
style = "bg:black bold white"
format = "[$time]($style) "

[git_branch]
style = "bg:black bold 85"
symbol = ' '
format = "[$symbol]($style)[$branch](bg:black 85)"
truncation_length = 8
truncation_symbol = "."

[git_status]
format = '[${ahead}${behind}${modified}${conflicted}${stashed}${deleted}${renamed}${staged}${untracked}]($style)'
style = "bg:black 85"
conflicted = "≠"
ahead = "⇡$count"
behind = "⇣$count"
diverged = "⇕"
untracked = "?"
stashed = "󰏖"
modified = '+'
staged = ""
renamed = "󱞸"
deleted = "󱡂"
up_to_date = "✔"

[cmd_duration]
disabled = true
min_time = 2_000
format = '[took $duration ]($style)'
style = 'bg:black bold yellow'

[jobs]
symbol = "▧ "
style = "bg:black blue"
format = "[ $number$symbol]($style)"

[python]
disabled = true
style = "bg:black yellow"
format = '[${virtualenv} ]($style)'
